{
 "title": "Kasboek ASN",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   { "name": "Search" },
   {
    "name": "Rekening",
    "query": "SELECT DISTINCT opdrachtgeversrekening AS __value, opdrachtgeversrekening AS __text FROM transacties_asn WHERE opdrachtgeversrekening is not null;"
   },
   {
    "name": "Afbij",
    "query": "SELECT DISTINCT af_bij AS __value, af_bij AS __text FROM transacties_asn WHERE af_bij is not null;"
   },
   {
    "name": "Mutatiesoort",
    "query": "SELECT DISTINCT mutatiesoort AS __value, mutatiesoort AS __text FROM transacties_asn WHERE rekening is not null;"
   }
  ]
 },
 "panels": [
  {
   "title": "Zoek suggesties",
   "type": "table",
   "gridPos": { "h": 15, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT word, similarity(word, '$search') AS similarity FROM words_asn WHERE word % '$Search'\nORDER BY similarity asc\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "Saldo",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH t1 as (\nSELECT $__time(\"boekingsdatum\"),\n  SUM(transactiebedrag::numeric) AS amount_new\nFROM transacties_asn t2\nLEFT JOIN mijn_rekeningen t3 ON t2.tegenrekeningnummer = t3.rekening\nWHERE t3.rekening IS null\nAND $__timeFilter(boekingsdatum)\nAND (tsv @@ websearch_to_tsquery('simple', '$Search') OR NULLIF('$Search', '') IS null)\nAND (t2.opdrachtgeversrekening::text IN ($Rekening) OR NULLIF(TRIM(CONCAT($Rekening)), '') IS null)\n--AND (t2.af_bij::text IN ($Afbij) OR NULLIF(TRIM(CONCAT($Afbij)), '') IS null)\n--AND (t2.mutatiesoort::text IN ($Mutatiesoort) OR NULLIF(TRIM(CONCAT($Mutatiesoort)), '') IS null)\nGROUP BY time\nORDER by time ASC\n), t4 AS (\n  SELECT time,\n    SUM(amount_new) over (ORDER BY time ASC rows between unbounded preceding AND current row) AS verloop\n  FROM t1)\nSELECT * FROM t4\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Totaal af",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  ABS(SUM(transactiebedrag::numeric)/100)::money AS total\nFROM transacties_asn t1\nLEFT JOIN mijn_rekeningen t2 ON t1.tegenrekeningnummer = t2.rekening\nWHERE t2.rekening IS null\nAND $__timeFilter(boekingsdatum)\nAND (tsv @@ websearch_to_tsquery('simple', '$Search') OR NULLIF('$Search', '') IS null)\nAND (t1.opdrachtgeversrekening::text IN ($Rekening) OR NULLIF(TRIM(CONCAT($Rekening)), '') IS null)\n--AND (tsv @@ websearch_to_tsquery('simple', '$Search') OR NULLIF('$Search', '') IS null)\n--AND (t1.rekening::text IN ($Rekening) OR NULLIF(TRIM(CONCAT($Rekening)), '') IS null)\n--AND (t1.af_bij::text IN ($Afbij) OR NULLIF(TRIM(CONCAT($Afbij)), '') IS null)\n--AND (t1.mutatiesoort::text IN ($Mutatiesoort) OR NULLIF(TRIM(CONCAT($Mutatiesoort)), '') IS null)\nAND SIGN(transactiebedrag::numeric) = -1;"
    }
   ]
  },
  {
   "title": "Totaal bij",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(transactiebedrag)/100 AS total\nFROM transacties_asn t1\nLEFT JOIN mijn_rekeningen t2 ON t1.tegenrekeningnummer = t2.rekening\nWHERE t2.rekening IS null\nAND $__timeFilter(boekingsdatum)\nAND (tsv @@ websearch_to_tsquery('simple', '$Search') OR NULLIF('$Search', '') IS null)\nAND (t1.opdrachtgeversrekening::text IN ($Rekening) OR NULLIF(TRIM(CONCAT($Rekening)), '') IS null)\n--AND (tsv @@ websearch_to_tsquery('simple', '$Search') OR NULLIF('$Search', '') IS null)\n--AND (t1.rekening::text IN ($Rekening) OR NULLIF(TRIM(CONCAT($Rekening)), '') IS null)\n--AND (t1.af_bij::text IN ($Afbij) OR NULLIF(TRIM(CONCAT($Afbij)), '') IS null)\n--AND (t1.mutatiesoort::text IN ($Mutatiesoort) OR NULLIF(TRIM(CONCAT($Mutatiesoort)), '') IS null)\n--AND af_bij = 'Af';\nAND SIGN(transactiebedrag::numeric) = 1;"
    }
   ]
  },
  {
   "title": "Overzicht af",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 14, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  ABS(SUM(transactiebedrag::numeric)/100)::money AS total,\n  CASE\n   WHEN naam_tegenrekening IS NULL THEN omschrijving\n   ELSE naam_tegenrekening\n   END naam_tegenrekening\nFROM transacties_asn t1\nLEFT JOIN mijn_rekeningen t2 ON t1.tegenrekeningnummer = t2.rekening\nWHERE t2.rekening IS null\nAND $__timeFilter(boekingsdatum)\nAND (tsv @@ websearch_to_tsquery('simple', '$Search') OR NULLIF('$Search', '') IS null)\nAND (t1.opdrachtgeversrekening::text IN ($Rekening) OR NULLIF(TRIM(CONCAT($Rekening)), '') IS null)\n--AND (tsv @@ websearch_to_tsquery('simple', '$Search') OR NULLIF('$Search', '') IS null)\n--AND (t1.rekening::text IN ($Rekening) OR NULLIF(TRIM(CONCAT($Rekening)), '') IS null)\n--AND (t1.af_bij::text IN ($Afbij) OR NULLIF(TRIM(CONCAT($Afbij)), '') IS null)\n--AND (t1.mutatiesoort::text IN ($Mutatiesoort) OR NULLIF(TRIM(CONCAT($Mutatiesoort)), '') IS null)\nAND SIGN(transactiebedrag::numeric) = -1\nGROUP BY 2\nORDER BY total DESC;"
    }
   ]
  },
  {
   "title": "Overzicht bij",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  ABS(SUM(transactiebedrag::numeric)/100)::money AS total,\nCASE\n  WHEN naam_tegenrekening IS NULL THEN omschrijving\nELSE naam_tegenrekening\n  END naam_tegenrekening\nFROM transacties_asn t1\nLEFT JOIN mijn_rekeningen t2 ON t1.tegenrekeningnummer = t2.rekening\nWHERE t2.rekening IS null\nAND $__timeFilter(boekingsdatum)\nAND (tsv @@ websearch_to_tsquery('simple', '$Search') OR NULLIF('$Search', '') IS null)\nAND (t1.opdrachtgeversrekening::text IN ($Rekening) OR NULLIF(TRIM(CONCAT($Rekening)), '') IS null)\n--AND (tsv @@ websearch_to_tsquery('simple', '$Search') OR NULLIF('$Search', '') IS null)\n--AND (t1.rekening::text IN ($Rekening) OR NULLIF(TRIM(CONCAT($Rekening)), '') IS null)\n--AND (t1.af_bij::text IN ($Afbij) OR NULLIF(TRIM(CONCAT($Afbij)), '') IS null)\n--AND (t1.mutatiesoort::text IN ($Mutatiesoort) OR NULLIF(TRIM(CONCAT($Mutatiesoort)), '') IS null)\nAND SIGN(transactiebedrag::numeric) = 1\nGROUP BY 2\nORDER BY total DESC;"
    }
   ]
  },
  {
   "title": "Bedrag",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT $__time(\"boekingsdatum\"),\n  SUM(transactiebedrag::numeric)/100 AS amount_new \nFROM transacties_asn t1\nLEFT JOIN mijn_rekeningen t2 ON t1.tegenrekeningnummer = t2.rekening\nWHERE t2.rekening IS null\nAND $__timeFilter(\"boekingsdatum\")\nAND (tsv @@ websearch_to_tsquery('simple', '$Search') OR NULLIF('$Search', '') IS null)\nAND (t1.opdrachtgeversrekening::text IN ($Rekening) OR NULLIF(TRIM(CONCAT($Rekening)), '') IS null)\n--AND (t1.af_bij::text IN ($Afbij) OR NULLIF(TRIM(CONCAT($Afbij)), '') IS null)\n--AND (t1.mutatiesoort::text IN ($Mutatiesoort) OR NULLIF(TRIM(CONCAT($Mutatiesoort)), '') IS null)\nGROUP BY boekingsdatum\nORDER BY boekingsdatum ASC;"
    }
   ]
  },
  {
   "title": "Aantal",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*), $__time(\"boekingsdatum\")\nFROM transacties_asn\nWHERE $__timeFilter(\"boekingsdatum\")\nAND (tsv @@ websearch_to_tsquery('simple', '$Search') OR NULLIF('$Search', '') IS null)\nAND (opdrachtgeversrekening::text IN ($Rekening) OR NULLIF(TRIM(CONCAT($Rekening)), '') IS null)\n--AND (af_bij::text IN ($Afbij) OR NULLIF(TRIM(CONCAT($Afbij)), '') IS null)\n--AND (mutatiesoort::text IN ($Mutatiesoort) OR NULLIF(TRIM(CONCAT($Mutatiesoort)), '') IS null)\nGROUP BY time\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Transacties",
   "type": "table",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT t1.boekingsdatum, t1.transactiebedrag/100 AS transactiebedrag, t1.naam_tegenrekening, t1.opdrachtgeversrekening, t1.tegenrekeningnummer, t1.omschrijving\nFROM transacties_asn t1\nLEFT JOIN mijn_rekeningen t2 ON t1.tegenrekeningnummer = t2.rekening\nWHERE t2.rekening IS null\nAND $__timeFilter(\"boekingsdatum\")\nAND (tsv @@ websearch_to_tsquery('simple', '$Search') OR NULLIF('$Search', '') IS null)\nAND (t1.opdrachtgeversrekening::text IN ($Rekening) OR NULLIF(TRIM(CONCAT($Rekening)), '') IS null)\n--AND (t1.af_bij::text IN ($Afbij) OR NULLIF(TRIM(CONCAT($Afbij)), '') IS null)\n--AND (t1.mutatiesoort::text IN ($Mutatiesoort) OR NULLIF(TRIM(CONCAT($Mutatiesoort)), '') IS null)\nORDER BY 1 DESC, 2\nLIMIT 1000;"
    }
   ]
  },
  {
   "title": "Overzicht naam_tegenrekening",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*), naam_tegenrekening\nFROM transacties_asn t1\nLEFT JOIN mijn_rekeningen t2 ON t1.tegenrekeningnummer = t2.rekening\nWHERE t2.rekening IS null\nAND $__timeFilter(boekingsdatum)\nAND (tsv @@ websearch_to_tsquery('simple', '$Search') OR NULLIF('$Search', '') IS null)\nAND (t1.opdrachtgeversrekening::text IN ($Rekening) OR NULLIF(TRIM(CONCAT($Rekening)), '') IS null)\nGROUP BY naam_tegenrekening\nORDER by count DESC\nLIMIT 15"
    }
   ]
  }
 ]
}