{
 "title": "Kasboek",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "opposing_name", "query": ".*, ^(hoogvliet).*" },
   { "name": "description", "query": ".*, aldi|albert" },
   { "name": "debit_credit", "query": ".*, Af, Bij" }
  ]
 },
 "panels": [
  {
   "title": "Amount",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__time(\"date\"), SUM(CASE WHEN debit_credit = 'Af' THEN - amount::numeric\n                WHEN debit_credit = 'Bij' THEN amount::numeric\n                ELSE 0\n           END) \nFROM perfin.transactions\nWHERE $__timeFilter(\"date\")\n  AND opposing_name ~* '($opposing_name)'\n  AND description ~* '($description)'\n  AND debit_credit ~* '($debit_credit)'\nGROUP BY date\nORDER BY date asc;"
    }
   ]
  },
  {
   "title": "Total af",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(amount) as total\nFROM perfin.transactions t1\nLEFT JOIN perfin.betaalrekeningen t2 ON t2.iban = t1.opposing_iban\nWHERE t2.iban IS NULL\n  and $__timeFilter(date)\n  AND opposing_name ~* '($opposing_name)'\n  AND description ~* '($description)'\n  AND debit_credit = 'Af'\n  --AND debit_credit = $debit_credit\n\n"
    }
   ]
  },
  {
   "title": "Total bij",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(amount) as total\nFROM perfin.transactions t1\nLEFT JOIN perfin.betaalrekeningen t2 ON t2.iban = t1.opposing_iban\nWHERE t2.iban IS NULL\n  AND $__timeFilter(date)\n  AND opposing_name ~* '($opposing_name)'\n  AND description ~* '($description)'\n  AND debit_credit = 'Bij'\n  --AND debit_credit = $debit_credit\n\n"
    }
   ]
  },
  {
   "title": "Total Af",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 14, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(amount) as total, opposing_name\nFROM perfin.transactions t1\nLEFT JOIN perfin.betaalrekeningen t2 ON t2.iban = t1.opposing_iban\nWHERE t2.iban IS NULL\n  AND $__timeFilter(date)\n  AND opposing_name ~* '($opposing_name)'\n  AND description ~* '($description)'\n  AND debit_credit = 'Af'\n  GROUP BY opposing_name\n  order by total desc\nLIMIT 15\n"
    }
   ]
  },
  {
   "title": "Total bij",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(amount) as total, opposing_name\nFROM perfin.transactions t1\nLEFT JOIN perfin.betaalrekeningen t2 ON t2.iban = t1.opposing_iban\nWHERE t2.iban IS NULL\n  AND $__timeFilter(date)\n  AND opposing_name ~* '($opposing_name)'\n  AND description ~* '($description)'\n  AND debit_credit = 'Bij'\n  GROUP BY opposing_name\n  order by total desc\nLIMIT 15\n"
    }
   ]
  },
  {
   "title": "Cumulative sum",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "with data as (\n  SELECT \"date\", SUM(CASE WHEN debit_credit = 'Af' THEN - amount::numeric\n                WHEN debit_credit = 'Bij' THEN amount::numeric\n                ELSE 0\n               END) as amount_new\nFROM perfin.transactions t1\nLEFT JOIN perfin.betaalrekeningen t2 ON t2.iban = t1.opposing_iban\nWHERE t2.iban IS NULL\n  AND $__timeFilter(date)\n  AND opposing_name ~* '$opposing_name'\n  AND description ~* '$description'\n  AND debit_credit ~* '$debit_credit'\nGROUP BY date\norder by date ASC\n), piet as (\n  select\n    date as time,\n    sum(amount_new) over (order by date asc rows between unbounded preceding and current row) as verloop\n  from data)\nselect * from piet\norder by time asc;"
    }
   ]
  },
  {
   "title": "Count",
   "type": "graph",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  count(*), $__time(\"date\")\nFROM perfin.transactions\nWHERE $__timeFilter(\"date\")\n  AND opposing_name ~* '($opposing_name)'\n  AND description ~* '($description)'\n  AND debit_credit ~* '($debit_credit)'\nGROUP BY time\nORDER BY time asc"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "table",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM perfin.transactions t1\nLEFT JOIN perfin.betaalrekeningen t2 ON t2.iban = t1.opposing_iban\nWHERE t2.iban IS NULL\n  AND $__timeFilter(date)\n  AND opposing_name ~* '$opposing_name'\n  AND description ~* '$description'\n  AND debit_credit ~* '$debit_credit'\norder by date desc\nLIMIT 1000\n"
    }
   ]
  },
  {
   "title": "Count per opposing_name",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*), opposing_name\nFROM perfin.transactions t1\nLEFT JOIN perfin.betaalrekeningen t2 ON t2.iban = t1.opposing_iban\nWHERE t2.iban IS NULL\n  AND $__timeFilter(date)\n  AND opposing_name ~* '($opposing_name)'\n  AND description ~* '($description)'\n  AND debit_credit ~* '($debit_credit)'\nGROUP BY opposing_name\norder by count desc\nLIMIT 15\n"
    }
   ]
  }
 ]
}