{
 "title": "Kasboek",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   { "name": "Search" },
   {
    "name": "Rekening",
    "query": "SELECT DISTINCT rekening AS __value, rekening AS __text FROM kasboek.transacties WHERE rekening is not null;"
   },
   {
    "name": "Afbij",
    "query": "SELECT DISTINCT af_bij AS __value, af_bij AS __text FROM kasboek.transacties WHERE af_bij is not null;"
   },
   {
    "name": "Mutatiesoort",
    "query": "SELECT DISTINCT mutatiesoort AS __value, mutatiesoort AS __text FROM kasboek.transacties WHERE rekening is not null;"
   }
  ]
 },
 "panels": [
  {
   "title": "Zoek suggesties",
   "type": "table",
   "gridPos": { "h": 15, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT word, similarity(word, '$search') AS similarity FROM kasboek.words WHERE word % '$Search'\nORDER BY similarity asc\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "Bedrag",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__time(\"datum\"),\n  SUM(CASE WHEN af_bij = 'Af' THEN - bedrag::numeric\n  WHEN af_bij = 'Bij' THEN bedrag::numeric\n  ELSE 0\nEND) \nFROM kasboek.transacties t1\nLEFT JOIN kasboek.mijn_rekeningen t2 ON t1.tegenrekening = t2.rekening\nWHERE t2.rekening IS null\nAND $__timeFilter(\"datum\")\nAND (tsvector @@ websearch_to_tsquery('simple', '$Search') OR NULLIF('$Search', '') IS null)\nAND (t1.rekening::text IN ($Rekening) OR NULLIF(TRIM(CONCAT($Rekening)), '') IS null)\nAND (t1.af_bij::text IN ($Afbij) OR NULLIF(TRIM(CONCAT($Afbij)), '') IS null)\nAND (t1.mutatiesoort::text IN ($Mutatiesoort) OR NULLIF(TRIM(CONCAT($Mutatiesoort)), '') IS null)\nGROUP BY datum\nORDER BY datum ASC;"
    }
   ]
  },
  {
   "title": "Totaal af",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(bedrag) AS total\nFROM kasboek.transacties t1\nLEFT JOIN kasboek.mijn_rekeningen t2 ON t1.tegenrekening = t2.rekening\nWHERE t2.rekening IS null\nAND $__timeFilter(datum)\nAND (tsvector @@ websearch_to_tsquery('simple', '$Search') OR NULLIF('$Search', '') IS null)\nAND (t1.rekening::text IN ($Rekening) OR NULLIF(TRIM(CONCAT($Rekening)), '') IS null)\nAND (t1.af_bij::text IN ($Afbij) OR NULLIF(TRIM(CONCAT($Afbij)), '') IS null)\nAND (t1.mutatiesoort::text IN ($Mutatiesoort) OR NULLIF(TRIM(CONCAT($Mutatiesoort)), '') IS null)\nAND af_bij = 'Af';"
    }
   ]
  },
  {
   "title": "Totaal bij",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(bedrag) AS total\nFROM kasboek.transacties t1\nLEFT JOIN kasboek.mijn_rekeningen t2 ON t1.tegenrekening = t2.rekening\nWHERE t2.rekening IS null\nAND $__timeFilter(datum)\nAND (tsvector @@ websearch_to_tsquery('simple', '$Search') OR NULLIF('$Search', '') IS null)\nAND (t1.rekening::text IN ($Rekening) OR NULLIF(TRIM(CONCAT($Rekening)), '') IS null)\nAND (t1.af_bij::text IN ($Afbij) OR NULLIF(TRIM(CONCAT($Afbij)), '') IS null)\nAND (t1.mutatiesoort::text IN ($Mutatiesoort) OR NULLIF(TRIM(CONCAT($Mutatiesoort)), '') IS null)\nAND af_bij = 'Bij';"
    }
   ]
  },
  {
   "title": "Overzicht af",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 14, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(bedrag) AS total, naam\nFROM kasboek.transacties t1\nLEFT JOIN kasboek.mijn_rekeningen t2 ON t1.tegenrekening = t2.rekening\nWHERE t2.rekening IS null\nAND $__timeFilter(datum)\nAND (tsvector @@ websearch_to_tsquery('simple', '$Search') OR NULLIF('$Search', '') IS null)\nAND (t1.rekening::text IN ($Rekening) OR NULLIF(TRIM(CONCAT($Rekening)), '') IS null)\nAND (af_bij::text IN ($Afbij) OR NULLIF(TRIM(CONCAT($Afbij)), '') IS null)\nAND (mutatiesoort::text IN ($Mutatiesoort) OR NULLIF(TRIM(CONCAT($Mutatiesoort)), '') IS null)\nAND af_bij = 'Af'\nGROUP BY naam\nORDER BY total DESC\nLIMIT 15\n"
    }
   ]
  },
  {
   "title": "Overzicht bij",
   "type": "table",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(bedrag) AS total, naam\nFROM kasboek.transacties t1\nLEFT JOIN kasboek.mijn_rekeningen t2 ON t1.tegenrekening = t2.rekening\nWHERE t2.rekening IS null\nAND $__timeFilter(datum)\nAND (tsvector @@ websearch_to_tsquery('simple', '$Search') OR NULLIF('$Search', '') IS null)\nAND (af_bij::text IN ($Afbij) OR NULLIF(TRIM(CONCAT($Afbij)), '') IS null)\nAND (mutatiesoort::text IN ($Mutatiesoort) OR NULLIF(TRIM(CONCAT($Mutatiesoort)), '') IS null)\nAND af_bij = 'Bij'\nGROUP BY naam\nORDER BY total DESC\nLIMIT 15"
    }
   ]
  },
  {
   "title": "Saldo",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 3, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "WITH t1 as (\nSELECT $__time(\"datum\"),\n  SUM(CASE WHEN af_bij = 'Af' THEN - bedrag::numeric\n  WHEN af_bij = 'Bij' THEN bedrag::numeric\n  ELSE 0\nEND) AS amount_new\nFROM kasboek.transacties t2\nLEFT JOIN kasboek.mijn_rekeningen t3 ON t2.tegenrekening = t3.rekening\nWHERE t3.rekening IS null\nAND $__timeFilter(datum)\nAND (tsvector @@ websearch_to_tsquery('simple', '$Search') OR NULLIF('$Search', '') IS null)\nAND (t2.rekening::text IN ($Rekening) OR NULLIF(TRIM(CONCAT($Rekening)), '') IS null)\nAND (t2.af_bij::text IN ($Afbij) OR NULLIF(TRIM(CONCAT($Afbij)), '') IS null)\nAND (t2.mutatiesoort::text IN ($Mutatiesoort) OR NULLIF(TRIM(CONCAT($Mutatiesoort)), '') IS null)\nGROUP BY time\nORDER by time ASC\n), t4 AS (\n  SELECT time,\n    SUM(amount_new) over (ORDER BY time ASC rows between unbounded preceding AND current row) AS verloop\n  FROM t1)\nSELECT * FROM t4\nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Aantal",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 3, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  count(*), $__time(\"datum\")\nFROM kasboek.transacties\nWHERE $__timeFilter(\"datum\")\nAND (tsvector @@ websearch_to_tsquery('simple', '$Search') OR NULLIF('$Search', '') IS null)\nAND (rekening::text IN ($Rekening) OR NULLIF(TRIM(CONCAT($Rekening)), '') IS null)\nAND (af_bij::text IN ($Afbij) OR NULLIF(TRIM(CONCAT($Afbij)), '') IS null)\nAND (mutatiesoort::text IN ($Mutatiesoort) OR NULLIF(TRIM(CONCAT($Mutatiesoort)), '') IS null)\nGROUP BY time\nORDER BY time ASC"
    }
   ]
  },
  {
   "title": "Transacties",
   "type": "table",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT t1.datum, t1.naam, t1.rekening, t1.tegenrekening, t1.code, t1.af_bij, t1.bedrag, t1.mutatiesoort, t1.mededeling\nFROM kasboek.transacties t1\nLEFT JOIN kasboek.mijn_rekeningen t2 ON t1.tegenrekening = t2.rekening\nWHERE t2.rekening IS null\nAND $__timeFilter(\"datum\")\nAND (tsvector @@ websearch_to_tsquery('simple', '$Search') OR NULLIF('$Search', '') IS null)\nAND (t1.rekening::text IN ($Rekening) OR NULLIF(TRIM(CONCAT($Rekening)), '') IS null)\nAND (t1.af_bij::text IN ($Afbij) OR NULLIF(TRIM(CONCAT($Afbij)), '') IS null)\nAND (t1.mutatiesoort::text IN ($Mutatiesoort) OR NULLIF(TRIM(CONCAT($Mutatiesoort)), '') IS null)\nORDER BY 1,2 ASC\nLIMIT 1000;"
    }
   ]
  },
  {
   "title": "Overzicht naam",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*), naam\nFROM kasboek.transacties t1\nLEFT JOIN kasboek.mijn_rekeningen t2 ON t1.tegenrekening = t2.rekening\nWHERE t2.rekening IS null\nAND $__timeFilter(datum)\nAND (tsvector @@ websearch_to_tsquery('simple', '$Search') OR NULLIF('$Search', '') IS null)\nAND (t1.rekening::text IN ($Rekening) OR NULLIF(TRIM(CONCAT($Rekening)), '') IS null)\nAND (t1.af_bij::text IN ($Afbij) OR NULLIF(TRIM(CONCAT($Afbij)), '') IS null)\nAND (t1.mutatiesoort::text IN ($Mutatiesoort) OR NULLIF(TRIM(CONCAT($Mutatiesoort)), '') IS null)\nGROUP BY naam\nORDER by count DESC\nLIMIT 15"
    }
   ]
  }
 ]
}